loggie-io/loggie

- pkg/core/sysconfig/config.go
- pkg/eventbus/listener/sink/listener.go
merge default interceptors defined in code to default interceptors defined in config
> Fix: optimize merge strategy of default interceptors 

- pkg/core/cfg/cfg.go
- pkg/core/cfg/cfg_test.go
* merge defaults configurations support recursion
eg:
defaults config:
```yaml
- type: file
fields:
cluster: test1
```
pipeline config:
```yaml
- type: file
fields:
topic: abc
```
**Before:**
merged:
```yaml
- type: file
fields:
topic: abc
```
**After this PR:**
merged:
```yaml
- type: file
fields:
cluster: test1
topic: abc
```
None
None
> Feat: merge defaults configurations support recursion

- pkg/util/time.go
* use local time in TimeFormatNow
None
None
> Feat: use local time format in pattern fields

- Dockerfile
- pkg/discovery/kubernetes/helper/kube.go
- don't install gcc-aarch64-linux-gnu for non-arm64 platform
- added VolumeMount.SubPath support
> Fix sub path

- pkg/discovery/kubernetes/helper/workload.go
- pkg/discovery/kubernetes/helper/workload_test.go
- pkg/interceptor/addk8smeta/interceptor.go
- pkg/util/pattern/k8smeta/k8meta.go
- pkg/util/pattern/pattern.go
* support workload.name and workload.kind in k8s fields
``` yaml
discovery:
enabled: true
k8sFields:
workload.name: "${_k8s.workload.name}"
workload.kind: "${_k8s.workload.kind}"
```
None
> Feat: support workload.name and workload.kind in k8s fields

- pkg/discovery/kubernetes/controller/controller.go
- pkg/discovery/kubernetes/controller/reconcile.go
- pkg/discovery/kubernetes/controller/selectpodhandler.go
- pkg/discovery/kubernetes/helper/kube.go
- pkg/discovery/kubernetes/helper/kube_test.go
- pkg/discovery/kubernetes/index/typepod.go
* logconfig/clusterlogconfig labelSelector support wildcard *
```
spec:
selector:
type: pod
labelSelector:
app: *
```
* support override annotation `logconfig.loggie.io/override` or `clusterlogconfig.loggie.io/override` in logconfig/clusterLogconfig
```
apiVersion: loggie.io/v1beta1
kind: LogConfig
metadata:
annotations:
clusterlogconfig.loggie.io/override: common
name: nginx
...
```
this nginx logConfig would override the common clusterLogconfig by the matched pod.
None
> Feat: logconfig/clusterlogconfig labelSelector support wildcard *

- pkg/core/event/event.go
fix addonMeta panic 
```
panic: assignment to entry in nil map
goroutine 57 [running]:
github.com/loggie-io/loggie/pkg/source/file.addonMetaProductFunc.func1({0x24a6848, 0xc000764f90})
/pkg/source/file/source.go:223 +0x3bf
github.com/loggie-io/loggie/pkg/source/codec.glob..func1.1({0x24a6848, 0xc000764f90})
/pkg/source/codec/codec.go:64 +0xa2
github.com/loggie-io/loggie/pkg/source/file.(*Job).ProductEvent(0xc00083e000, 0x29872, {0x10000, 0xc00052d769, 0x366d3c0}, {0xc0004f2000, 0x5b, 0x4d025e})
/pkg/source/file/job.go:345 +0x7a6
github.com/loggie-io/loggie/pkg/source/file/process.(*LineProcessor).Process(0x10000, {0x10000, 0x100000000000c93}, 0xc0003eb4a0)
/pkg/source/file/process/line.go:52 +0x1c7
github.com/loggie-io/loggie/pkg/source/file.NewProcessChain.func2(0xc00007a070) …
```
> fix addonMeta panic

- pkg/interceptor/transformer/transformer.go
* change result.Success to result.Drop when dropEvent() in transformer interceptor
> Fix: change result.Success to result.Drop when dropEvent() 

- pkg/interceptor/normalize/rename.go
if obj.GetPath not found use obj.Get
Which issue(s) this PR fixes:
Fixes https://github.com/loggie-io/loggie/issues/295
> fix: cannot rename fields which containing '.' 

- pkg/discovery/kubernetes/controller/controller.go
* Fix: type assert panic when deleting pod recieve DeletedFinalStateUnknown objects
> Fix: deleting pod recieve DeletedFinalStateUnknown objects

- pkg/pipeline/pipeline.go
> Fix empty fields after the field is renamed in normalize interceptor

- pkg/include/include.go
- pkg/interceptor/schema/config.go
- pkg/interceptor/schema/interceptor.go
- pkg/interceptor/schema/pipeline.yml
- pkg/interceptor/transformer/action/timestamp.go
- pkg/source/file/config.go
- pkg/source/prometheus_exporter/prometheus.go
- pkg/util/pattern/pattern.go
- pkg/util/pattern/pattern_test.go
- pkg/util/time/format.go
- pkg/util/time/time.go
- pkg/util/time/time_test.go
* add schema interceptor
Usage:
```
---
interceptors:
- type: schema
addMeta:
timestamp:
key: "@timestamp"
remap:
body:
key: message
---
interceptors:
- type: schema
addMeta:
timestamp:
key: "_timestamp_"
location: Local
layout: 2006-01-02T15:04:05Z07:00
remap:
body:
key: _log_
```
> Feat: add schema interceptor

- pkg/discovery/kubernetes/helper/kube.go
- pkg/discovery/kubernetes/runtime/cri.go
- pkg/discovery/kubernetes/runtime/docker.go
- pkg/discovery/kubernetes/runtime/runtime.go
* support collect log files from pod pv
Note:
set `rootFsCollectionEnabled` to true, and container runtime should be `docker`.
Fixes https://github.com/loggie-io/loggie/issues/329
> Feat: support collect log files from pod pv

- pkg/core/cfg/cfg.go
- pkg/core/interceptor/config.go
- pkg/core/reloader/reload.go
- pkg/core/source/config.go
- pkg/discovery/kubernetes/controller/config.go
- pkg/discovery/kubernetes/controller/reconcile.go
- pkg/discovery/kubernetes/controller/selectpodhandler.go
- pkg/discovery/kubernetes/external/dynamiclogs.go
- pkg/discovery/kubernetes/helper/config.go
- pkg/discovery/kubernetes/helper/kube.go
- pkg/discovery/kubernetes/index/typepod.go
- pkg/discovery/kubernetes/index/typepod_test.go
- pkg/discovery/kubernetes/kubernetes.go
- pkg/eventbus/listener/filesource/listener.go
- pkg/pipeline/pipeline.go
- pkg/source/codec/config.go
- pkg/source/file/config.go
- pkg/source/file/job.go
- pkg/source/file/read.go
- pkg/source/file/source.go
- pkg/source/file/task.go
- pkg/source/file/watch.go
- test/configuration/pipeline_test.go
* Support dynamic setting of file source paths in kubernetes cluster, reduce configuration rendering caused by pod create/update/delete, thereby reducing the number of reloads.
Enable this by set dynamicContainerLog to true:
```
discovery:
enabled: false
kubernetes:
dynamicContainerLog: true
```
Fixes https://github.com/loggie-io/loggie/issues/333
> Feat: support dynamic container logs

- pkg/util/eventops/event_test.go
- pkg/util/runtime/object.go
- pkg/util/runtime/select.go
- pkg/util/runtime/select_test.go
* support [a.b] when fields key is a.b other than a nested fields
None
> Fix: support [a.b] when fields key is a.b other than a nested fields

- pkg/source/kubernetes_event/eventer.go
修复kubeevent 选主的问题，如果两个pod在同一个node上，使用nodename容易冲突，所以用hostname
> fix  LeaderElection Identity

- pkg/interceptor/transformer/action/regex.go
- pkg/interceptor/transformer/example/pipeline.yml
* regex set args `to` other than `key` in transformer interceptor
> Fix: regex set args `to` other than `key` in transformer interceptor

- loggie.yml
- pkg/discovery/kubernetes/controller/selectpodhandler.go
- pkg/interceptor/transformer/action/fmtkey.go
- pkg/util/runtime/object.go
- pkg/util/runtime/object_test.go
* add fmtKey() action in transformer interceptor
Usage: 
```
interceptors:
actions:
- action: fmtKey()
regex: foo.bar/(.*)
replace: pre-${1}
```
- regex: match header keys
- replace: reformat the key to `replace`
> Feat: add fmtKey() in transformer interceptor

- pkg/sink/elasticsearch/client.go
- pkg/sink/elasticsearch/config.go
* add opType param in elasticsearch sink, we should add `opType: create` when setting up a datastream in elasticsearch
```
sink:
type: elasticsearch
hosts: ["elasticsearch1:9200", "elasticsearch2:9200", "elasticsearch3:9200"]
index: "log-${fields.service}-${+YYYY.MM.DD}"
opType: create
```
> Feat: add opType in elasticsearch sink

- pkg/discovery/kubernetes/controller/selectpod_test.go
- pkg/discovery/kubernetes/controller/selectpodhandler.go
* Reformat the key of label/annotation/env in the pod, the value remains unchanged
Example: According to the regular, extract values, and then add a prefix
Assumption: pod label is `aa.bb/foo=bar`
Configure:
```
reformatKeys:
label:
- regex: aa.bb/(.*)
replace: pre-${1}
```
Result: the field added to the log is `pre-foo=bar`
> Feat: add reformatKeys in matchFields

- pkg/core/interceptor/extension.go
- pkg/interceptor/logalert/alerting.go
- pkg/interceptor/logalert/config.go
- pkg/pipeline/manage.go
- pkg/pipeline/pipeline.go
* when interceptor order is not configured, the interceptor maintains the order in the pipelines configuration.
> Fix: interceptor order in pipelines

- pkg/core/source/config.go
- pkg/pipeline/pipeline.go
* add fieldsFromPath in source
assume:
```
cat /tmp/foo
---
bar
```
when we add `fieldsFromPath` below:
```yaml
- name: local
sources:
- type: file
fieldsFromPath:
test: /tmp/foo
```
then, events would add the fields:
```json
{
"body": "xxxx",
"fields": {
"test": "bar"
}
}
```
> Feat: add fieldsFromPath in source

- pkg/interceptor/transformer/action/action.go
* add dropIfError in transformer interceptor
```yaml
interceptors:
actions:
- action: jsonDecode(body)
dropIfError: true
```
> Feat: add dropIfError in transformer interceptor

- pkg/eventbus/base.go
- pkg/eventbus/listener/info/listener.go
- pkg/include/include.go
* add info listener for scape loggie version
```yaml
listeners:
info: ~
```
metrics:
```
loggie_info_status{version="v1.3.0"} 1
```
> Feat: add info listener for scape loggie version

- pkg/interceptor/transformer/action/split.go
- pkg/interceptor/transformer/action/split_test.go
* add split action in transformer interceptor
```yaml
interceptors:
actions:
- action: split(body)
separator: "|"
keys: ["time", "order", "service", "price"]
```
Using the above split configuration can convert the log from:
```
2021-08-08|U12345|storeCenter|13.14
```
to:
```
"time": "2021-08-08"
"order": "U12345"
"service": "storeCenter"
"price: "13.14"
```
> Feat: add split action in transformer interceptor

- pkg/util/eventops/event.go
fix copy action,   - action: copy(body, res)
issues : #419 
test code
```
func TestCopyBody(t *testing.T) {
assertions := assert.New(t)
type fields struct {
from string
to   string
}
type args struct {
e api.Event
}
tests := []struct {
name   string
fields fields
args   args
}{
{
name: "Copy body",
fields: fields{
from: "body",
to:   "res",
},
args: args{
e: event.NewEvent(map[string]interface{}{
"aa": "hello",
}, []byte("this is body")),
},
},
}
for _, tt := range tests {
t.Run(tt.name, func(t1 *testing.T) {
t := &Copy{
from: tt.fields.from,
to:   tt.fields.to,
}
err := t.act(tt.args.e)
println(tt.args.e.String())
assertions.NoError(err)
})
}
}
```
fix before:
```
=== RUN   TestCopyBody
=== RUN   TestCopyBody/Copy_body
header:{"aa":"hello","res":"dGhpcyBpcyBib2R5"}, body:"this is body" …
```
> FIX: copy action: body

- pkg/source/kubernetes_event/eventer.go
* fix kubeEvent source panic when enabled watchLatestEvents
Fixes #458 
```docs
None
```
> fix(source): panic when kubeEvent Series is nil

- pkg/interceptor/transformer/condition/conditions.go
- pkg/interceptor/transformer/condition/conditions_test.go
- Fix:  contain(level,ERROR) parse failed in transformer condition.
> Fix: parse condition failed when contain ERROR

- pkg/interceptor/limit/clock.go
- pkg/interceptor/limit/interceptor.go
- pkg/interceptor/limit/limiter.go
* ratelimit interceptor
Fixes #509
```docs
highPrecision: true
> The high precision mode of the rate limiting component can be enabled, but it comes with the cost of increased CPU usage. Consider enabling it when the limited QPS exceeds 20,000
```
> fix: ratelimit may lose precision on Linux

- pkg/source/file/config.go
- pkg/source/file/job.go
- pkg/source/file/process/line.go
- pkg/source/file/process/loop.go
* file source
```docs
maxSingleLineBytes: 67108864
```
> fix: large line may cause oom

- pkg/sink/dev/config.go
- pkg/sink/dev/sink.go
- add `resultStatus` in dev sink.
- add `/api/v1/pipeline/{pipelineName}/sink/dev`?status=success/fail/drop API，which can set dev sink return status dynamically.
> Feat: add resultStatus in dev sink to simulate failure, drop

- pkg/sink/franz/config.go
- pkg/sink/franz/pipeline.yml
- pkg/sink/franz/sink.go
- pkg/sink/kafka/config.go
- pkg/sink/kafka/sink.go
```
sink:
type: kafka
brokers: ["127.0.0.1:6400"]
topic: "log-${fields.topic}"
ignoreUnknownTopicOrPartition: true
```
if ignoreUnknownTopicOrPartition: true, ignore error when kafka topic or partion not exsit.
> Feat: add ignoreUnknownTopicOrPartition in kafka sink

- pkg/interceptor/maxbytes/interceptor.go
> fix(interceptor): Optimizes maxbytes interceptions

- pkg/interceptor/transformer/condition/equal.go
场景：
当 transformer interceptor 的 equal(key, target) 条件，key 设置为 body 时，eventops.Get 函数返回的 interface{} 的底层类型是 []byte，与 eq.value 的 string 类型不匹配，导致 == 判断失败。
处理方法：
当获取到 eventops.Get 返回值时进行类型断言判断是否是 []byte 类型，如果是则进行类型转换，再进行比较。
> Fix: Convert to string type when returning [] byte type

- pkg/interceptor/transformer/action/set.go
- pkg/interceptor/transformer/action/set_test.go
* [interceptor/transformer] feat:support setFloat/setInt/setBool, it is the same with set + strconv, but set the value once
Fixes #621
```docs
interceptor: support setFloat/setInt/setBool
1. an older configuration is：
name: setEmpty
actions:
- if: NOT exist(count)
then:
- action: set(count, 0)
- action: strconv(count, float)
- action: return()
else:
- action: return()
2. the newly configuration is: 
name: setEmpty
actions:
- if: NOT exist(count)
then:
- action: setFloat(count, 0)
- action: return()
else:
- action: return()
```
> [interceptor/transformer] feat:support setFloat/setInt/setBool

- pkg/interceptor/transformer/action/replace.go
- pkg/interceptor/transformer/action/replace_test.go
*  add transformer `replace` action
Fixes #630
```yaml
interceptors:
actions:
- action: replace(body)
old: "3"
new: "W"
...
```
input:
```
{
"body": "2023/09/05 12:32:01 error zap.go:66: 192.168.0.1 54Ce5d87-b94C-C40a-74a7-9cd375289334"
}
```
output:
```
{
"body": "202W/09/05 12:W2:01 error zap.go:66: 192.168.0.1 54ce5d87-b94c-c40a-74a7-9cdW75289WW4",
}
```
> feat: Add transformer replace action

- pkg/interceptor/transformer/condition/match.go
fix:Fix comma split bug
\d{1,4}.\d{1,4}.\d{1,4}
> fix:Fix comma split bug

- pkg/source/file/watch.go
* When there is only one source and it is enabled, globalWatcher is nil. If the helper interface is requested later, core will occur.
```
pipelines:
- name: local
sources:
- type: file
enabled: false
name: demo
paths:
- /home/zhanglei/*.log
fields:
"@topic": "loggie"
interceptors:
- type: normalize
name: global
processors:
- addMeta: ~
- add:
fields:
"metadata.module": "loggie"
"metadata.type": ""
"metadata.version": 1.444
- rename:
convert:
- from: "meta.systemState.collectTime"
to: "colleciton.@collectiontime"
- from: "body"
to: "collection.@message"
- from: "meta.systemState.filename"
to: "collection.@path"
- from: "meta.systemState.lineNumber"
to: "collection.@rownumber"
- drop:
targets: ["meta"]
sink:
type: router
hosts:
- "192.168.110.117:7070"
max_client: 1
```
Fixes #
```
if …
```
> fix:fix globalWatcher is nil,when source is enable

- pkg/ops/helper/help.go
- test/benchmark/sink/elasticsearch/elasticsearch.go
> chore: unnecessary use of fmt.Sprintf

- pkg/sink/sls/config.go
- pkg/sink/sls/credentialprovider.go
- pkg/sink/sls/sls.go
Use STS(Security Token Service[1]) Token can reduce the risk of long-term access key (AccessKey) leakage. The token will automatically expire after expiration date, so it need to be periodically refreshed.
There 2 ways for a user to retrieve a STS token:
- AssumeRole/AssumeRoleWithSAML/AssumeRoleWithOIDC [2]
- Access ECS metadata server [3] on an ECS instance, 
So we create a new credentialprovider to execute commands to allow end users to extend the STS refreshment without modifying the loggie itself.
1. https://www.alibabacloud.com/help/en/ram/product-overview/what-is-sts 
2. https://www.alibabacloud.com/help/en/ram/developer-reference/api-sts-2015-04-01-dir-role-assuming/ 
3. https://www.alibabacloud.com/help/en/ecs/user-guide/obtain-a-temporary-authorization-token
* Allow to use SLS …
> feat: add STS Token support for the SLS sink

- pkg/interceptor/retry/interceptor.go
Proposed Changes:
kafka/sink.go
Which issue(s) this PR fixes:
Fixes https://github.com/loggie-io/loggie/issues/668
Additional documentation:
None
> fix: retry interceptor goroutine blocking

- pkg/source/file/watch.go
Fix: insert registry when existAckOffset is zero
> Fix: insert registry when existAckOffset is zero
