loggie-io/loggie

loggie.yml, pkg/control/controller.go, pkg/core/reloader/reload.go, pkg/eventbus/base.go, pkg/eventbus/listener/pipeline/listener.go, pkg/include/include.go, pkg/pipeline/pipeline.go, pkg/source/file/config.go, pkg/source/file/source.go, pkg/source/file/task.go, pkg/source/file/watch.go, pkg/util/array.go
1. file source stop timeout
2. monitor pipeline
=> fix: file source stop fail

pkg/control/controller.go, pkg/eventbus/base.go, pkg/eventbus/listener/pipeline/listener.go, pkg/pipeline/pipeline.go, pkg/source/file/multilines.go, pkg/source/file/watch.go
=> fix: pipeline metric

pkg/interceptor/normalize/copy.go
```
interceptors:
- type: normalize
processors:
- copy:
convert:
- from: "abc"
to: "efg"
```
=> Feat(interceptor): enhance normalize interceptor, add copy processor

pkg/source/dev/config.go, pkg/source/dev/source.go
```yaml
sources:
- type: "dev"
name: "a"
qps: 1000
byteSize: 1024
```
=> Feat(source): add QPS and size configuration support on dev source

pkg/discovery/kubernetes/apis/loggie/v1beta1/clusterlogconfig_types.go, pkg/discovery/kubernetes/controller/selectpodhandler.go, pkg/discovery/kubernetes/helper/config.go
=> Feat(discovery): Add spec.interceptors and spec.sink params in ClusterLogConfig/LogConfig CRD

pkg/include/include.go, pkg/sink/codec/raw/raw.go
=> Feat(sink): adding raw sink codec #136

cmd/loggie/main.go, pkg/control/config.go, pkg/core/cfg/cfg.go, pkg/core/reloader/reload.go
Signed-off-by: chaunceyjiang <chaunceyjiang@gmail.com>
Fix #130
=> Reading system and pipeline configurations from specific env

pkg/discovery/kubernetes/apis/loggie/v1beta1/clusterlogconfig_types.go, pkg/discovery/kubernetes/controller/controller.go, pkg/discovery/kubernetes/controller/reconcile.go, pkg/discovery/kubernetes/controller/selectclusterhandler.go, pkg/discovery/kubernetes/controller/selectnodehandler.go, pkg/discovery/kubernetes/controller/selectpodhandler.go, pkg/discovery/kubernetes/index/typecluster.go, pkg/discovery/kubernetes/index/typenode.go, pkg/discovery/kubernetes/index/typepod.go
=> Feat:  Flush pipelines configuration when sink or interceptor is updated reference by the LogConfig 

cmd/loggie/main.go, pkg/discovery/kubernetes/controller/controller.go, pkg/source/kubernetes_event/config.go, pkg/source/kubernetes_event/eventer.go, vendor/k8s.io/client-go/tools/leaderelection/OWNERS, vendor/k8s.io/client-go/tools/leaderelection/healthzadaptor.go, vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go, vendor/k8s.io/client-go/tools/leaderelection/metrics.go, vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go, vendor/k8s.io/client-go/tools/leaderelection/resourcelock/endpointslock.go, vendor/k8s.io/client-go/tools/leaderelection/resourcelock/interface.go, vendor/k8s.io/client-go/tools/leaderelection/resourcelock/leaselock.go, vendor/k8s.io/client-go/tools/leaderelection/resourcelock/multilock.go, vendor/modules.txt
1. add leader election
2. support watch the latest events when restart
3. add blacklist of namespaces
=> Feat: update kubeEvent source

pkg/include/include.go, pkg/source/file/job.go, pkg/source/file/process.go, pkg/source/file/process/lastline.go, pkg/source/file/process/line.go, pkg/source/file/process/loop.go, pkg/source/file/process/source.go, pkg/source/file/read.go, pkg/source/file/watch.go
https://github.com/loggie-io/loggie/issues/154#issuecomment-1101047364
=> refactor: reader process chain

pkg/pipeline/pipeline.go
cache env for optimizing performance  when using `fieldsFromEnv`
=> Feat(source): cache env for optimizing performance when using fieldsFromEnv

.github/workflows/build-docker-image.yml
- build image named after [master, master-${CommitID}] when pushing to master
- build image named after tag's name when creating a tag
=> Feat: docker image ci

pkg/eventbus/listener/sink/listener.go
Fix panic in sink/listener consume method
=> Fix(Eventbus): panic in sink/listener consume method

pkg/core/log/global.go
* add callerSkipCount logger flag
* add noColor logger flag
None
-  [ ] TODO
=> Feat: add callerSkipCount and noColor logger flag

pkg/core/log/global.go
**[breaking]**
* we do not print log as json format now
* refactor logger
None
=> Feat: update log.jsonFormat default to false

pkg/source/file/watch.go
=> fix: watcher stop timeout bug

cmd/loggie/main.go, pkg/control/config.go
* add logs for initial pipelines configuration
None
None
=> Feat: add logs for initial pipelines configuration

pkg/sink/file/multiwriter.go, pkg/sink/file/multiwriter_test.go
=> fix(sink): fix MultiFileWriter write

pkg/control/config.go, pkg/core/log/global.go, pkg/core/reloader/reload.go
* add IsDebugLevel method in logger for debug
* add log in reload when diff pipeline config
None
None
=> Feat: add debug log in reload when diff pipeline config

pkg/pipeline/pipeline.go
1. source stop may block
2. reduce duplicate data after reload
NONE
NONE
=> fix: pipeline stop may block

pkg/interceptor/normalize/jsondecode.go, pkg/interceptor/normalize/processor.go, pkg/interceptor/normalize/regex.go, pkg/interceptor/normalize/split.go
* ignore error in some normalize processors when we set ignoreError to true
None
=> Feat: add ignoreError in normalize interceptor

pkg/sink/file/sink.go
=> file sink support codec

pkg/core/sink/interceptor.go, pkg/core/source/interceptor.go, pkg/interceptor/maxbytes/config.go, pkg/pipeline/pipeline.go, pkg/source/file/process.go
fix unstable interceptor sort
Fixes #210 
NONE
=> fix: unstable interceptor sort

pkg/interceptor/normalize/processor.go, pkg/interceptor/normalize/split.go
* fix LogErrorWithIgnore params 
None
None
=> Fix: fix LogErrorWithIgnore params

pkg/source/grpc/batch.go
fix grpc source ack panic
Fixes #213 
NONE
=> fix: grpc source ack panic

pkg/core/cfg/cfg.go
* fix defaults value unmerged when multiple sources
None
None
=> Fix: merge defaults when multiple sources

.github/workflows/build-docker-image.yml, Dockerfile
* support multi-arch image
*
*
Fixes #
https://github.com/loggie-io/loggie/issues/226
```docs
```
=> feat: support multi-arch

pkg/discovery/kubernetes/external/cluster.go, pkg/discovery/kubernetes/kubernetes.go, pkg/interceptor/addk8smeta/interceptor.go, pkg/interceptor/addk8smeta/workload.go, pkg/interceptor/addk8smeta/workload_test.go
*
*
*
resolve  #220 
fix #222
```docs
```
=> Feat(interceptor): addk8smeta support workload

pkg/core/source/config.go, pkg/discovery/kubernetes/controller/config.go, pkg/discovery/kubernetes/controller/selectpodhandler.go, pkg/include/include.go, pkg/pipeline/pipeline.go, pkg/source/codec/codec.go, pkg/source/codec/config.go, pkg/source/codec/json/json.go, pkg/source/codec/regex/regex.go, pkg/source/file/job.go, pkg/source/file/source.go
* add source codec json and regex
* fix header removed in multiline
* add `parseStdout` in kubernetes discovery
None
=> Feat: add source codec

Dockerfile
*
*
*
Fixes #
multi-arch-dockerfile
```docs
```
=> fix-multi-arch-dockerfile

pkg/discovery/kubernetes/controller/selectpodhandler.go
* Fix: set updated path to file source
None
None
=> Fix: set updated path to file source

pkg/discovery/kubernetes/index/typepod.go
* omit empty pipeline configs
None
None
=> Fix: omit empty pipeline configs

pkg/discovery/kubernetes/controller/selectpodhandler.go
* add removed k8s fields for compatibility
None
None
=> Fix: add removed k8s fields for compatibility

.github/workflows/build-docker-image.yml
* build images when git push to release branch
None
None
=> Feat: build images when git push to release branch

CONTRIBUTING.md, README.md, README_cn.md
=> Docs: optimize README

pkg/sink/codec/json/json.go
* set beatsFormat timestamp to UTC
None
None
=> Fix: set beatsFormat timestamp to UTC

pkg/core/cfg/cfg.go
* change the type in mergeComonCfg since we update the yaml lib(#242)
None
=> Fix: change the type in mergeComonCfg since we update the yaml lib(#242)

pkg/core/cfg/cfg.go
* change the type in mergeComonCfg since we update the yaml lib(#242)
None
None
=> Fix: change the type in mergeComonCfg 

pkg/pipeline/pipeline.go
fix pipeline clean data error
Fixes #276
=> fix: pipeline clean data error

pkg/sink/elasticsearch/elasticsearch.go
=> Refactor: es sink error log

pkg/pipeline/pipeline.go, pkg/source/file/watch.go, pkg/util/execute.go
fix stop pipeline may timeout because too many source
=> fix pipeline stop timeout

Dockerfile, pkg/source/grpc/batch.go
* grpc source: move private fields from header to meta
=> Fix(grpc source): move private fields from header to meta

pkg/pipeline/manage.go, pkg/source/file/watch.go
=> fix stop pipeline panic

go.mod, go.sum, vendor/gopkg.in/natefinch/lumberjack.v2/lumberjack.go, vendor/modules.txt
*  make default file permissions from 600 to 644
Fixes #
None
```docs
```
=> Feat(sink): make default file permissions from 600 to 644

pkg/discovery/kubernetes/index/typecluster.go, pkg/discovery/kubernetes/index/typenode.go
* fix clusterlogconfig npe when deleting
=> Fix(discovery): fix clusterlogconfig npe when deleting

pkg/interceptor/retry/interceptor.go, pkg/pipeline/manage.go, pkg/pipeline/pipeline.go, pkg/source/file/config.go, pkg/source/file/read.go, pkg/source/file/source.go, pkg/source/file/watch.go
=> Fix pipeline source

pkg/source/dev/config.go, pkg/source/dev/example/pipeline.yml, pkg/source/dev/source.go
* add `eventsTotal` fields to control the events counts.
```yaml
sources:
- type: dev
name: demo
eventsTotal: 10000
byteSize: 1024
qps: 100
```
None
=> Feat(dev source): support total events in dev source

pkg/eventbus/listener/queue/listener.go, pkg/eventbus/listener/sys/listener.go
=> fix prometheus export topic

pkg/pipeline/pipeline.go, pkg/source/file/process/loop.go, pkg/source/file/task.go, pkg/source/file/watch.go
* fix big line collect may block
* fix watchTask stop may block
=> Fix file source exception

pkg/interceptor/maxbytes/config.go
=> Fix: recover maxbytes order

pkg/discovery/kubernetes/controller/selectpodhandler.go
* check if pod is ready when handle logconfig events
=> Fix: check if pod is ready when handle logconfig events

pkg/control/config.go, pkg/core/reloader/reload.go, test/configuration/pipeline_test.go
* stop pipeline when config is empty
=> Fix: stop pipeline when config is empty

cmd/loggie/main.go
* ignore file error in main.go
=> Fix: ignore file error in main.go

pkg/core/reloader/reload.go
* sort source and interceptor when reload, related to https://github.com/loggie-io/loggie/pull/317
=> Fix: sort source and interceptor when reload

pkg/interceptor/transformer/action/action.go, pkg/interceptor/transformer/example/pipeline.yml
* Fix: missing extra args in transformer interceptor, related to https://github.com/loggie-io/loggie/pull/317
=> Fix: missing extra args in transformer interceptor

pkg/interceptor/transformer/action/print.go
* do not update events in action print() of transformer interceptor
=> Fix: do not update events in action print() of transformer interceptor

pkg/pipeline/manage.go, pkg/pipeline/pipeline.go, pkg/source/file/ack.go, pkg/source/file/source.go
=> fix: ack stop block

pkg/sink/loki/loki.go
* replace fields token string '. / -' to '_'
* because loki does not support . / -
Fixes #
https://github.com/loggie-io/loggie/issues/342
=> feat(loki): replace fields token string '. / -' to '_'

pkg/util/encode.go
=> add gbk18030

cmd/loggie/main.go, pkg/control/controller.go, pkg/control/http.go, pkg/core/reloader/http.go, pkg/core/reloader/reload.go, pkg/eventbus/base.go, pkg/eventbus/listener/filewatcher/listener.go, pkg/ops/helper/help.go, pkg/source/file/http.go, pkg/source/file/watch.go
* add api /api/v1/helper for debugging
Fixes #290
=> Feat: add api /api/v1/helper for debugging

pkg/discovery/kubernetes/kubernetes.go, pkg/discovery/kubernetes/runtime/runtime.go
=> Add no rootfsEnabled auto scan

pkg/source/kubernetes_event/eventer.go
=> fix kubeevent retry

pkg/sink/loki/config.go, pkg/sink/loki/loki.go
http custom headers added in request sent to loki.
*
*
*
Fixes #
```docs
```
=> feat：loki custom headers

pkg/source/codec/json/json.go, pkg/source/codec/json/json_test.go, pkg/source/codec/regex/regex.go, pkg/source/codec/regex/regex_test.go, pkg/source/file/multilines.go
修复开启parseStdout 丢失stream 和time的问题
=> fix(source): Fix the problem of missing stream and time

pkg/discovery/kubernetes/helper/kube.go
=> fix(discovery): support static pod

pkg/core/cfg/cfg.go, pkg/pipeline/pipeline.go
* check if config is nil in setDefault.
* check if properties is nil when validateComponent.
=> Fix: npe in cfg.go

loggie.yml
=> fix(core): Set default runtime

pkg/discovery/kubernetes/controller/selectpodhandler.go, pkg/discovery/kubernetes/helper/kube.go, pkg/discovery/kubernetes/index/typepod.go, pkg/discovery/kubernetes/index/typepod_test.go
* do not ignore pod events when container id is changed
=> Fix: do not ignore pod events when container id is changed

pkg/source/file/config.go
* validate multiline pattern to avoid panic
=> Fix: validate multiline pattern

pkg/ops/helper/help.go
* `/api/v1/help?detail=all&status=pending`: Only show log files which is being collected (including 0 progress), ignore the collection progress 100%, NaN% and ignored.
=> Feat: add status=pending query param in /api/v1/help

pkg/source/file/job.go
* change file size is smaller than firstNBytesForIdentifier to debug
=> Feat: change file size is smaller than firstNBytesForIdentifier to debug

pkg/core/api/base.go, pkg/core/source/config.go, pkg/discovery/kubernetes/controller/selectpodhandler.go, pkg/discovery/kubernetes/index/typepod.go, pkg/pipeline/pipeline.go, pkg/source/file/source.go
* Fix missing fields in multiline
* Fix override the same pipeline and souce when set dynamicContainerLogs to true
=> Fix: missing logs when enabled dynamicContainerLogs

pkg/source/kubernetes_event/config.go, pkg/source/kubernetes_event/config_test.go, pkg/source/kubernetes_event/eventer.go
修复kubeevent 开启LatestEventsEnabled 可能造成的数据丢失
=> fix(source): Fixed the risk of data loss due to startTime when kubeevnet collection restarts

pkg/interceptor/retry/interceptor.go, pkg/sink/loki/loki.go
* interceptor retry meta npe
* add log when marshal loki request failed
=> Fix: interceptor retry meta npe

pkg/source/file/multilines.go
* add jobFields when multiline flush
=> Fix: add jobFields when multiline flush

doc/changelog/CHANGELOG-v1.md
* add release v1.3.0 changelog
=> Chore: add release v1.3.0 changelog

.github/workflows/release.yml, Makefile
=> Chore: add release action

.github/workflows/release.yml, Makefile, doc/changelog/CHANGELOG-v1.md
=> Feat add release action

go.mod, go.sum, pkg/interceptor/maxbytes/interceptor.go, vendor/github.com/thinkeridea/go-extend/LICENSE, vendor/github.com/thinkeridea/go-extend/exunicode/exutf8/doc.go, vendor/github.com/thinkeridea/go-extend/exunicode/exutf8/utf8.go, vendor/modules.txt
* Fix: garbled characters caused by intercepting a string in maxbytes interceptor
=> Fix: garbled characters caused by intercepting a string

.github/workflows/release.yml, Makefile
=> Chore: remove loggie bin suffix

pkg/core/event/event.go, pkg/sink/elasticsearch/client.go, pkg/sink/elasticsearch/elasticsearch.go, pkg/sink/elasticsearch/pipeline.yml, pkg/sink/kafka/pipeline.yml, pkg/sink/kafka/sink.go, pkg/util/pattern/pattern.go, pkg/util/pattern/pattern_test.go
*  add render object strict
* skip event in elasticsearch sink when index pattern render failed
* skip event in kafka sink when topic pattern render failed
=> Fix: add render object strict

pkg/source/file/source.go
* add source fields to filesource listener
=> Fix: add source fields to filesource listener

pkg/discovery/kubernetes/runtime/docker.go
* fetch logs file from UpperDir when enabled rootfs collection
=> Feat: fetch logs file from UpperDir when enabled rootfs collection

pkg/sink/kafka/config.go, pkg/sink/kafka/sink.go
* customized kafka sink partition key
*
*
Fixes #
```docs
```
=> feat：customized kafka sink partition key

pkg/sink/kafka/config.go, pkg/sink/kafka/sink.go, pkg/source/kafka/config.go, pkg/source/kafka/kafka.go
* Kafka source supports sasl. Configuration similar with kafka sink.
Fixes #
```docs
```
=> feat: Kafka source supports sasl.

pkg/include/include.go, pkg/source/elasticsearch/client.go, pkg/source/elasticsearch/config.go, pkg/source/elasticsearch/elasticsearch.go, pkg/source/elasticsearch/persistence.go
* add elasticsearch source
Fixes #198
Support pull data from elastic regularly，the configuration is as follows:
```yaml
pipelines:
- name: local
sources:
- type: elasticsearch
name: elastic
hosts:
- "localhost:9200"
- "localhost:9201"
username: "bob"
password: "bob"
schema: ""
sniff: false
gzip: true
includeFields: # pull selected field
- Title
- Content
- Author
excludeFields: # exclude selected field
- Content
query: | # elastic query phrases
{
"match": {"Title": "bob"}
}
index: "blog*"
size: 10 # data size per fetch
interval: 30s # pull data frequency
timeout: 5s # pull timeout
db: 
flushTimeout: 2s # persistent the elastic pull location frequency
cleanInactiveTimeout: 24h # delete the db record after the time
cleanScanInterval: 1h # check the expired db record frequency
sink:
type: …
```
=> feat(source): support elasticsearch

pkg/include/include.go, pkg/sink/zinc/config.go, pkg/sink/zinc/sink.go
* add zinc sink
Fixes #
ZincSearch is the simplest and easiest search system to get up and running. It's an open source easy-to-use search engine to solves your observability needs.
```docs
pipelines:
- name: local
sources:
- type: file
name: demo
paths:
- /tmp/log/*.log
fields:
topic: "loggie"
sink:
type: zinc
host: "http://127.0.0.1:4080"
username: admin
password: Complexpass#123
index: "demo"
codec:
pretty: false
```
=> Feat: add zinc sink

pkg/interceptor/transformer/action/jsonencode.go, pkg/interceptor/transformer/action/jsonencode_test.go
* add transformer jsonEncode aciton
=> Feat: add jsonencode action in transformer interceptor

pkg/sink/loki/config.go, pkg/sink/loki/loki.go
* loki sink https
Fixes #
```docs
example
sink:
type: loki
url: https://xxxxxx
insecureSkipVerify: true
```
=> loki sink https insecureSkipVerify

pkg/sink/franz/config.go
=> feature(sink): Add franz-go support

pkg/source/file/persistence.go, pkg/source/file/persistence_test.go, pkg/source/file/watch.go
=> Feat big file

pkg/source/elasticsearch/client.go, pkg/source/elasticsearch/config.go, pkg/source/elasticsearch/persistence.go, pkg/source/elasticsearch/pipeline.yml
* Support multiple index as indices.
* Update default loggie db index pattern.
=> Feat: update elasticsearch source

pkg/source/file/watch.go
fix file watcher: repeated invalid calculation of filewatch metric
=> fix: repeated invalid calculation of filewatch metric

pkg/discovery/kubernetes/controller/config.go, pkg/discovery/kubernetes/controller/selectpodhandler.go, pkg/discovery/kubernetes/kubernetes.go, pkg/discovery/kubernetes/runtime/runtime.go
* add containerRuntime: none
* update parseStdout regex
=> Feat: add containerRuntime none; update parseStdout regex

pkg/pipeline/pipeline.go
* fix pipeline restart when sink fails
*
*
Fixes #
```docs
```
=> fix pipeline restart

pkg/discovery/kubernetes/controller/config.go, pkg/discovery/kubernetes/controller/controller.go, pkg/discovery/kubernetes/controller/selectnodehandler.go, pkg/discovery/kubernetes/controller/selectpodhandler.go
* add typePodFields and typeNodeFields to LogConfig/ClusterLogConfig
=> Feat: add typePodFields and typeNodeFields to LogConfig/ClusterLogConfig

loggie.yml, pipelines.yml, pkg/pipeline/pipeline.go, pkg/sink/codec/codec.go, pkg/sink/codec/config.go, pkg/sink/codec/json/json.go, pkg/sink/codec/json/json_test.go, pkg/sink/codec/raw/raw.go, pkg/sink/dev/config.go, pkg/sink/dev/sink.go
* sink codec support printEvents
```yaml
sink:
type: dev
codec:
type: json
printEvents: true
pretty: true
```
=> Feat: sink codec support printEvents

pkg/discovery/kubernetes/controller/reconcile.go, pkg/discovery/kubernetes/controller/selectpodhandler.go
* refactor kubernetes events record
=> Fix: refactor kubernetes events record

pkg/discovery/kubernetes/apis/loggie/v1beta1/clusterlogconfig_types.go, pkg/discovery/kubernetes/controller/selectpod_test.go, pkg/discovery/kubernetes/controller/selectpodhandler.go, pkg/discovery/kubernetes/index/typepod.go
* logconfig/clusterlogconfig queue
*
*
Fixes #
```docs
```
=> add logconfig/clusterlogconfig queue

pkg/source/kafka/config.go
* rename kafka source config SASL to sasl 
Fixes #463
=> Feat: rename kafka source config SASL to sasl

loggie.yml, pkg/source/elasticsearch/client.go, pkg/source/elasticsearch/config.go, pkg/source/elasticsearch/persistence.go, pkg/source/elasticsearch/pipeline.yml
* added sortBy field in es source
*
*
Fixes #468
- sortBy: array, required
```docs
sortBy:
- fields: "@timestamp"
ascending: true
- fields: "_id"
ascending: true
```
=> Feat: added sortBy field in es source

pkg/discovery/kubernetes/controller/controller.go, pkg/discovery/kubernetes/controller/selectpodhandler.go
* ignore logconfig with sidecar injection annotation
=> Feat: ignore logconfig with sidecar injection annotation

pkg/interceptor/transformer/action/tostr.go, pkg/interceptor/transformer/action/tostr_test.go
* add toStr function in transformer interceptor
*
*
Fixes #
```docs
```
=> Feat: add toStr function in transformer interceptor

README.md, README_cn.md
=> docs: update Readme

pkg/sink/dev/sink.go, pkg/source/kafka/config.go, pkg/source/kafka/kafka.go
* add clientId in Kafka source
=> Feat: add clientId in Kafka source

pkg/source/grpc/batch.go
* Fix grpc batch out-of-order data streams
Fixes #470 
```docs
```
=> Fix: grpc batch out-of-order data streams

pkg/util/persistence/driver/sqlite.go
=> Fix: sqlite is locked

Dockerfile, Dockerfile.badger
* Dockerfile
* Dockerfile.badger
Fixes https://github.com/loggie-io/loggie/issues/540
None
=> fix:multi arch other command can't use

pkg/sink/franz/config.go, pkg/sink/franz/sink.go, pkg/sink/kafka/config.go, pkg/sink/kafka/sink.go
```
sink:
type: kafka
topic: log-${foo}
ifRenderTopicFailed:
defaultTopic: log-default
```
=> Feat: add default topic if render kafka topic failed

pkg/sink/elasticsearch/client.go, pkg/sink/elasticsearch/config.go, pkg/sink/elasticsearch/pipeline.yml, pkg/sink/franz/sink.go, pkg/sink/kafka/sink.go
```
type: elasticsearch
hosts: ["localhost:9200"]
index: "log-${fields.topic}-${+YYYY.MM.DD}"
ifRenderIndexFailed:
defaultIndex: log-default
```
=> Feat: add default index if render elasticsearch index failed

pkg/eventbus/export/logger/logger.go
修复关闭监控日志输出时，listener等处理被堵塞的问题。
=> 修改日志关闭时bug

pkg/discovery/kubernetes/runtime/cri.go
Currently, when rootFsCollectionEnabled is enabled, and the containerRuntime is containerd. loggie collects container logs by accessing the mapped host directory("/proc/{pid}/root"), However, when the containerd's runtime is not the "runc", this way may not work. this PR adds support specifically for kata as the containerd runtime.
This PR adds support specifically for kata as the containerd runtime. as the kata runtime, we are able to collect logs from 
/run/kata-containers/shared/sandboxes/<sandbox-id>/shared/<container-id>/rootfs in the corresponding hosts.
=> feat: Add kata runtime support for log collection

pkg/source/kafka/config.go, pkg/source/kafka/kafka.go
=> Feat: support multiple topics in kafka source

pkg/discovery/kubernetes/controller/config.go, pkg/discovery/kubernetes/controller/selectpodhandler.go
```
discovery:
enabled: false
kubernetes:
fieldsOmitEmpty: true
```
=> Feat: support omit empty fields in k8s discovery

loggie.yml, pkg/source/file/config.go, pkg/source/file/watch.go
```docs
cleanFiles:
cleanUnfinished: true
```
=> Feat: add cheanUnfinished in cleanFiles

pkg/sink/franz/config.go, pkg/sink/franz/sink.go
=> Feat 230607 franz kafka partion key

Makefile, pkg/include/all.go, pkg/include/core.go
usage:
```
make build EXT_BUILD_TAGS=include_core
```
or:
```
make build-in-badger EXT_BUILD_TAGS=include_core
```
=> Feat: support build core components of Loggie

pkg/source/file/config.go, pkg/source/file/source.go
```docs
addonMeta: true
addonMetaSchema:
underRoot: true
key: "@metadata"
fields:
pipeline: "${_meta.pipeline}"
source: "${_meta.source}"
filename: "${_meta.filename}"
timestamp: "${_meta.timestamp}"
offset: "${_meta.offset}"
bytes: "${_meta.bytes}"
line: "${_meta.line}"
hostname: "${_meta.hostname}"            
```
=> Feat: add addonMetaSchema in file source

loggie.yml, pkg/core/source/config.go, pkg/pipeline/pipeline.go
```docs
- type: file
timestampKey: "@timestamp"
bodyKey: "message"
```
=> Feat: add timestamp and bodyKey in source

pkg/discovery/kubernetes/helper/kube.go
#341 requires that container runtime should be `docker`. In this PR, containerd is supported.
Fixes #486
=> Fix: support log files from pv when container runtime is containerd

pkg/interceptor/transformer/action/replace.go, pkg/interceptor/transformer/action/replace_test.go
Add transformer `replaceRegex` action. 
like:  https://grafana.com/docs/loki/latest/clients/promtail/stages/replace/
Fixes #630
```docs
interceptors:
actions:
- action: replaceRegex(body)  
expression: <string> // The RE2 regular expression. Each named capture group will be replaced with the value given in `replace`
replace: <string> //
...
```
`expression` needs to be a [Go RE2 regex string](https://github.com/google/re2/wiki/Syntax).
`replace` is a replace value.
use:
```
actions:
- action: replaceRegex(body)  // SSN
expression: '([0-9]{3}-[0-9]{2}-[0-9]{4})'
replace: '*SSN*'
- action: replaceRegex(body)  // IP4
expression: '(\d{1,3}[.]\d{1,3}[.]\d{1,3}[.]\d{1,3})'
replace: '*IP4*' 
- action: replaceRegex(body)  // email
expression: '([\w\.=-]+@[\w\.-]+\.[\w]{2,64})' …
```
=> feat: support transformer replaceRegex

pkg/sink/franz/sink.go
修复sink插件franzKafka无法自动创建topic的问题
=> 修复sink插件franzKafka无法自动创建topic的问题

pkg/discovery/kubernetes/helper/kube.go
* k8s集群的容器运行时是docker时，如果直接将nfs挂载到待采集的容器内，loggie渲染路径时，获取的是upper层目录，实际上该目录下是没有期望的文件的，而应该采集 mount上来的nfs目录。k8s源码见https://github.com/kubernetes/kubernetes/blob/6aac45ff1e99068e834ba3b93b673530cf62c007/pkg/volume/nfs/nfs.go#L202
* 测试过contianerd的容器运行时不存在这种情况，原因是渲染路径时使用的是/proc下面的目录，因此没有这个问题。
*
Fixes #
```docs
```
=> Fix: nfs volumes in docker runtime issue
